server :
  port: 9099

spring :
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.219.115:3306/certificatcal?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    password: tlqkfdk156
    username: miewone
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        foramt_sql: true


serviceKey : "/kWN9ikcMx1GS6QaLwTHsOeZ99pucYQmjXTTwQRJmTUWOhapdp8yD6/UQ+Wx045jZFup+zHz7IEM5vxle1hQJA=="